### PR TITLE
Update Terraria.Localization.Content.fr-FR.tModLoader.json

### PR DESCRIPTION
**Pull request by orian34**
French translation update

### CODE REVIEW

**Comment by orian34** [comment]
I haven't finished it, I'll comment when it's complete

**Comment by orian34** [comment]
THERE IT IS!
Dunno if the lines should stay commented out or not. I only translated

**Comment by Jofairden** [comment]
I don't think they should stay commented, not sure why they are anyway.

**Comment by Jofairden** [comment]
@JavidPack made a python script for the translations. I believe the commented lines are placeholder and meant to be uncommented when implemented.

**Comment by JavidPack** [comment]
Yeah, can you remove the "// " from all the lines that you translated?

**Pull request merged**
