### PR TITLE
Auto-download/update dependencies

### PR DESCRIPTION
**Pull request by Itorius**
### Description of the Change

Added the ability for users for download/update mods with their dependencies, thus eliminating the potential complaints about mods not working due to missing dependencies.

### Applicable Issues

I replaced downloading code `UIModDownloadItem` with a call to `UIModBrowser.DownloadMods` which *might* break some things, but from the testing which I have done it seems to work.

### CODE REVIEW

**Comment by Itorius** [comment]
### Bug
When downloading mods without dependencies it shows 'Missing mods [nothing] required by [mod].'

**Comment by Jofairden** [comment]
@Itorius In hindsight, do you have time to finish this sometime soon? We could then include it in next release.

**Comment by Agrair** [comment]
I tried to fix this on my tML fork, try and see if that works

**Comment by Jofairden** [comment]
@JavidPack  @Chicken-Bones Do we still like to have this feature?

**Comment by Jofairden** [comment]
@Itorius I implemented this in cd84dfc 
Your current PR could not be accepted due to current code changes in the mod browser and download manager.

**Pull request closed without merging**
