### PR TITLE
 Update Chinese translation

### PR DESCRIPTION
**Pull request by Dierney**
Well, I'm glad I finally understand the "LoadErrorMajorVersionMismatch"......

### CODE REVIEW

**Comment by Jofairden** [comment]
Maybe it's helpful if you join our chat? I mean, if changes keep coming you keep updating the translation files which is kind of tedious. It would be much better to just to it at the end no?

**Comment by Dierney** [comment]
> 也许如果你加入我们的聊天会有帮助吗？我的意思是，如果不断变化，你会不断更新翻译文件，这有点乏味。到最后没有它会好得多吗？

Yup, but I don't know what to do. Pull request is the quickest way I can think of.

**Comment by Dierney** [comment]
> Maybe it's helpful if you join our chat? I mean, if changes keep coming you keep updating the translation files which is kind of tedious. It would be much better to just to it at the end no?

Yup, but I don't know what to do. Pull request is the quickest way I can think of.

**Comment by JavidPack** [comment]
Thanks again for being very diligent with this.

**Comment by Jofairden** [comment]
> Yup, but I don't know what to do. Pull request is the quickest way I can think of.

What I meant is, waiting before translating because we keep adding new strings

**Comment by Dierney** [comment]
> What I meant is, waiting before translating because we keep adding new strings

Well, no problem. Just notify me before the new version is released.

**Pull request merged**
