### PR TITLE
Collector's Edition Fix

### PR DESCRIPTION
**Pull request by DarkLight66**
### Description of the Change

* Prevents the carrot from the Collector's Edition version of Terraria from replacing the item on the fourth slot on the hotbar on character creation after the SetupStartInventory hook is called.

### Applicable Issues

#347

### CODE REVIEW

**Comment by Jofairden** [comment]
What's the `newPlayer ` bool for? SetupStartInventory is meant for newly created characters, so it's redundant.

**Comment by Leemyy** [comment]
SetupStartInventory also gets called when a mediumcore character dies, so I'd assume that's why it's needed.

**Comment by Jofairden** [comment]
And why does it get called? Mediumcore characters should drop items upon death

**Comment by JavidPack** [comment]
Don't they get a free copper pick and other items when they respawn?

**Comment by Leemyy** [comment]
Yes, it's called to give you back the starting tools. Otherwise you could easily end up softlocked, because your stuff dropped in a place you can't reach without tools. Also, when a mediumcore character dies all items that are part of the starting inventory will get deleted, instead of getting dropped.

I'm assuming that DarkLight added this flag, because the pet is only given to a character upon creation, but not when they respawn.

**Comment by Jofairden** [comment]
In that case, I think it is better to have the boolean suggest mediumcore death rather than character creation, as mediumcore death in this context is the special circumstance. If you do that, I'll accept it.

**Comment by JavidPack** [comment]
Looks good.

**Pull request merged**
