### PR TITLE
Add SetChatButtons and OnChatButtonClicked to GlobalNPC (Resolves #68)

### LINKED ISSUE #68: SetChatButtons and OnChatButtonClicked not implemented in GlobalNPC
Both SetChatButtons and OnChatButtonClicked are not implemented in the GlobalNPC class.

### PR DESCRIPTION
**Pull request by Murfalo**
Finally got around to actually fixing this

### CODE REVIEW

**Comment by Murfalo** [comment]
Yep!  I tested the hooks using example mod and everything appears to work as expected.

**Comment by Jofairden** [comment]
We'd appreciate it if you could include the changes to ExampleMod to showcase usage of these hooks in GlobalNPC.

**Comment by Murfalo** [comment]
No problem.  I'll hopefully have time to amend the commit by the end of the week.

**Comment by Jofairden** [comment]
@Murfalo  are you still planning on doing something with this?

**Comment by Murfalo** [comment]
Hi @Jofairden - I'm hoping to have some free time to spend on tModLoader stuff in about two or three weeks.

**Comment by Murfalo** [comment]
Hi @Jofairden - Looks like a great deal has changed since I opened this PR.  Gonna close it since at this point it's probably best to just redo the hook implementation with the newer system.

**Pull request closed without merging**
